import type {
  ApprovalItem,
  CronJob,
  DashboardSnapshot,
  GatewayHealth,
  IncidentEvent,
  Mission,
  SessionSummary,
} from "@/lib/types";

const now = Date.now();

const missions: Mission[] = [
  {
    id: "flow_4c77fa",
    title: "汇总昨夜 Telegram 队列",
    status: "running",
    source: "session",
    startedAt: new Date(now - 14 * 60_000).toISOString(),
    elapsedMs: 14 * 60_000,
    lastEventAt: new Date(now - 7_000).toISOString(),
    lastReason: "正在向会话流式输出回复",
    childCount: 2,
    parentLabel: "main / telegram",
    sessionId: "sess_main_telegram_1",
    agentId: "main",
    stale: false,
    raw: { mock: true },
  },
  {
    id: "flow_91ab2d",
    title: "每周文档同步",
    status: "blocked",
    source: "cron",
    startedAt: new Date(now - 62 * 60_000).toISOString(),
    elapsedMs: 62 * 60_000,
    lastEventAt: new Date(now - 11 * 60_000).toISOString(),
    lastReason: "等待执行审批以推送变更",
    childCount: 0,
    parentLabel: "cron/nightly-docs",
    sessionId: "sess_docs_12",
    agentId: "docs",
    stale: false,
    raw: { mock: true },
  },
  {
    id: "flow_77cd31",
    title: "飞书事故回顾",
    status: "failed",
    source: "background",
    startedAt: new Date(now - 3 * 60 * 60_000).toISOString(),
    elapsedMs: 12 * 60_000,
    lastEventAt: new Date(now - 2 * 60 * 60_000).toISOString(),
    lastReason: "工具调用期间网关连接中断",
    childCount: 1,
    parentLabel: "background/reports",
    sessionId: "sess_feishu_8",
    agentId: "ops",
    stale: true,
    raw: { mock: true },
  },
];

const sessions: SessionSummary[] = [
  {
    id: "sess_main_telegram_1",
    label: "主会话 / Telegram / Boss",
    agentName: "main",
    channel: "telegram",
    source: "message",
    model: "gpt-5.4",
    lastMessageAt: new Date(now - 22_000).toISOString(),
    lastToolAt: new Date(now - 18_000).toISOString(),
    currentActivity: "正在起草回复并读取任务上下文",
    state: "active",
    recentErrors: false,
    stale: false,
    preview: "需要昨夜摘要和当前被阻塞的审批。",
    raw: { mock: true },
  },
  {
    id: "sess_docs_12",
    label: "文档 Agent / cron",
    agentName: "docs",
    channel: "cron",
    source: "cron",
    model: "gpt-4.1",
    lastMessageAt: new Date(now - 12 * 60_000).toISOString(),
    lastToolAt: new Date(now - 11 * 60_000).toISOString(),
    currentActivity: "等待执行审批",
    state: "blocked",
    recentErrors: false,
    stale: false,
    preview: "补丁已生成，git push 需要审批。",
    raw: { mock: true },
  },
  {
    id: "sess_feishu_8",
    label: "运维 / 飞书跟进",
    agentName: "ops",
    channel: "feishu",
    source: "background",
    model: "claude-sonnet",
    lastMessageAt: new Date(now - 2 * 60 * 60_000).toISOString(),
    lastToolAt: new Date(now - 2 * 60 * 60_000).toISOString(),
    currentActivity: "暂无进展信号",
    state: "idle",
    recentErrors: true,
    stale: true,
    preview: "网关重连后需要重试。",
    raw: { mock: true },
  },
];

const approvals: ApprovalItem[] = [
  {
    id: "exec_approval_1",
    kind: "exec",
    requester: "docs",
    sessionId: "sess_docs_12",
    agentId: "docs",
    action: "git push origin codex/openclaw-doc-sync",
    host: "local",
    riskSummary: "文档 cron 任务准备向外部仓库执行 git push",
    waitingSince: new Date(now - 9 * 60_000).toISOString(),
    waitingMs: 9 * 60_000,
    raw: { command: "git push origin codex/openclaw-doc-sync" },
  },
  {
    id: "plugin_approval_2",
    kind: "plugin",
    requester: "main",
    sessionId: "sess_main_telegram_1",
    agentId: "main",
    action: "feishu_doc.create",
    host: "gateway",
    riskSummary: "通过插件桥写入一份新的飞书文档",
    waitingSince: new Date(now - 2 * 60_000).toISOString(),
    waitingMs: 2 * 60_000,
    raw: { plugin: "feishu_doc", action: "create" },
  },
];

const cronJobs: CronJob[] = [
  {
    id: "cron_1",
    title: "夜间文档同步",
    schedule: "0 2 * * *",
    nextRunAt: new Date(now + 5 * 60 * 60_000).toISOString(),
    lastRunAt: new Date(now - 62 * 60_000).toISOString(),
    lastStatus: "blocked",
    consecutiveFailures: 0,
    linkedTarget: "docs / cron",
    failing: false,
    runs: [
      {
        id: "run_1",
        status: "blocked",
        startedAt: new Date(now - 62 * 60_000).toISOString(),
        error: "等待执行审批",
        raw: { mock: true },
      },
    ],
    raw: { mock: true },
  },
  {
    id: "cron_2",
    title: "Telegram 心跳",
    schedule: "*/30 * * * *",
    nextRunAt: new Date(now + 11 * 60_000).toISOString(),
    lastRunAt: new Date(now - 19 * 60_000).toISOString(),
    lastStatus: "ok",
    consecutiveFailures: 0,
    linkedTarget: "main / telegram",
    failing: false,
    runs: [],
    raw: { mock: true },
  },
  {
    id: "cron_3",
    title: "飞书事故监控",
    schedule: "*/15 * * * *",
    nextRunAt: new Date(now + 4 * 60_000).toISOString(),
    lastRunAt: new Date(now - 15 * 60_000).toISOString(),
    lastStatus: "error",
    consecutiveFailures: 3,
    linkedTarget: "ops / feishu",
    failing: true,
    runs: [
      {
        id: "run_2",
        status: "error",
        startedAt: new Date(now - 15 * 60_000).toISOString(),
        finishedAt: new Date(now - 14 * 60_000).toISOString(),
        error: "通知步骤连接被重置",
        raw: { mock: true },
      },
    ],
    raw: { mock: true },
  },
];

const incidents: IncidentEvent[] = [
  {
    id: "incident_1",
    type: "exec.approval.requested",
    title: "收到执行审批请求",
    description: "文档 cron 任务因 git push 审批而被阻塞。",
    severity: "warning",
    occurredAt: new Date(now - 9 * 60_000).toISOString(),
    source: "gateway",
    relatedId: "exec_approval_1",
    raw: { mock: true },
  },
  {
    id: "incident_2",
    type: "cron.run.failed",
    title: "Cron 运行失败",
    description: "飞书事故监控已连续失败三次。",
    severity: "error",
    occurredAt: new Date(now - 14 * 60_000).toISOString(),
    source: "cron",
    relatedId: "cron_3",
    raw: { mock: true },
  },
  {
    id: "incident_3",
    type: "session.message",
    title: "会话活跃",
    description: "主 Telegram 会话产生了一条新消息。",
    severity: "info",
    occurredAt: new Date(now - 22_000).toISOString(),
    source: "gateway",
    relatedId: "sess_main_telegram_1",
    raw: { mock: true },
  },
];

export function getMockHealth(): GatewayHealth {
  return {
    status: "degraded",
    mode: "mock",
    connected: false,
    gatewayUrl: "ws://127.0.0.1:18789",
    identity: "mock-local",
    message: "实时 OpenClaw 数据面不可用，当前处于模拟模式。",
    lastEventAt: new Date(now - 20_000).toISOString(),
    lastSnapshotAt: new Date().toISOString(),
    stale: false,
    sources: [
      {
        key: "gateway",
        label: "网关 RPC",
        available: false,
        stale: false,
        error: "模拟模式",
      },
      {
        key: "events",
        label: "网关事件",
        available: false,
        stale: false,
        error: "模拟模式",
      },
      {
        key: "flows",
        label: "Flows CLI",
        available: true,
        stale: false,
        lastSuccessAt: new Date().toISOString(),
      },
    ],
  };
}

export function getMockSnapshot(): DashboardSnapshot {
  const health = getMockHealth();

  return {
    generatedAt: new Date().toISOString(),
    health,
    sources: health.sources,
    overview: {
      activeSessions: sessions.filter((session) => session.state !== "idle").length,
      runningTasks: missions.filter((mission) => mission.status === "running").length,
      blockedTasks: missions.filter((mission) => mission.status === "blocked").length,
      failedTasks: missions.filter((mission) => mission.status === "failed").length,
      pendingExecApprovals: approvals.filter((item) => item.kind === "exec").length,
      pendingPluginApprovals: approvals.filter((item) => item.kind === "plugin").length,
      cronTotal: cronJobs.length,
      cronFailing: cronJobs.filter((job) => job.failing).length,
      nextDueAt: cronJobs.map((job) => job.nextRunAt).filter(Boolean).sort()[0],
    },
    missions,
    sessions,
    approvals,
    cronJobs,
    incidents,
  };
}
